name: API-TEST

on:
  push:
    branches:
      - main
      - resetassured-httpbin
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: |
          echo "check if httpbin is up" >> $GITHUB_STEP_SUMMARY
          curl -s -o /dev/null -w "%{http_code}\n" https://httpbin.org/
          echo "Running mvn test" >> $GITHUB_STEP_SUMMARY 
          cd resetassured-httpbin
          mvn test

      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-report
          path: 'resetassured-httpbin/target/surefire-reports/TEST-*.xml'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'resetassured-httpbin/target/surefire-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

