name: API-TEST

on:
  push:
    branches:
      - main
      - resetassured-httpbin
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Check connections
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "<<<<<<check if httpbin is reachable>>>>>>"
          curl -i https://httpbin.org/get
          echo "<<<<<<List OPENAPI models>>>>>>"
          curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"

      - name: Maven test
        id: maven-test
        continue-on-error: true
        timeout-minutes: 15
        run: |
          cd resetassured-httpbin
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn --version
          echo "Running tests with debug output:"
          mvn test -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2

      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        if: steps.maven-test.outcome == 'success' || steps.maven-test.outcome == 'failure'
        with:
          name: test-report
          path: 'resetassured-httpbin/target/surefire-reports/TEST-*.xml'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: steps.maven-test.outcome == 'success' || steps.maven-test.outcome == 'failure'
        with:
          report_paths: 'resetassured-httpbin/target/surefire-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

