name: API-TEST

on:
  push:
    branches:
      - main
      - resetassured-httpbin
  workflow_call:

permissions:
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Specify the Java version you want
          distribution: 'adopt'  # Use AdoptOpenJDK distribution
          maven-version: '3.9.9'  # Specify the Maven version you want

      # - name: Start local httpbin
      #   run: |
      #     docker run -d -p 8585:80 --rm --name httpbin kennethreitz/httpbin
      #     echo "Waiting for httpbin to start..."
      #     sleep 5
      #     curl -i http://localhost:8585/get

      - name: Check connections
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "<<<<<<check if httpbin is reachable>>>>>>"
          curl -i https://httpbin.org/get
          echo "<<<<<<List OPENAPI models>>>>>>"
          curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"

      - name: Maven test
        id: maven-test
        continue-on-error: true
        timeout-minutes: 15
        run: |
          cd resetassured-httpbin
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn --version
          echo "Running tests with debug output:"
          mvn test -Dtest.environment=production

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: steps.maven-test.outcome == 'success' || steps.maven-test.outcome == 'failure'
        with:
          report_paths: "resetassured-httpbin/target/surefire-reports/TEST-*.xml"
